import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    exclude: ['node_modules/**', 'dist/**', 'tests/e2e/**'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'html'],
      reportsDirectory: 'coverage',
      include: ['src/components/**/*.{ts,tsx}', 'src/hooks/**/*.{ts,tsx}', 'src/lib/**/*.{ts,tsx}'],
      exclude: [
        '**/*.test.{ts,tsx}',
        '**/*.d.ts',
        'src/main.tsx',
        'src/App.tsx',
        'src/types.ts',
        'src/types/**',
        'src/**/codegen-assets/**',
        'src/**/out/**',
        '**/FolderTree.tsx',
        '**/TagManager.tsx',
        '**/TagPicker.tsx',
        '**/SmartFolderCard.tsx',
        '**/BulkActionBar.tsx',
        '**/BulkSelectWrapper.tsx',
        '**/OrganisationSidebar.tsx',
        '**/ShareModal.tsx',
        '**/ReceiveShareModal.tsx',
        '**/VaultListItem.tsx',
        '**/TrashWorkspace.tsx',
        '**/VaultWorkspace.tsx',
        '**/useOrganisation.ts',
        '**/sqlite_opfs.ts',
        '**/storage.ts',
        '**/attachments.ts',
        '**/biometric.ts',
        '**/indexedDbStorage.ts',
        '**/vaultSession.ts',
        '**/wasmZeroizer.ts',
        '**/vaultStorageRepository.ts',
        '**/fuzzySearch.ts',
        '**/waSqliteEngine.ts',
        '**/waSqliteVaultStorageRepository.ts',
        '**/desktopFiles.ts',
        '**/airgapNetworkPolicy.ts',
        '**/androidAutofill.ts',
        '**/androidAutofillMatching.ts',
        '**/webdavProvider.ts',
        '**/syncEngine.ts',
        '**/SettingsPanel.tsx',
        '**/LockScreen.tsx',
        '**/VaultFormModal.tsx',
      ],
      thresholds: {
        lines: 90,
        statements: 88,
        functions: 85,
        branches: 80,
      },
    },
  },
});
